name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: make run

      - name: Run a one-line script
        run: echo Hello, world!
